# Generated by Django 4.2.7 on 2023-12-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='procedencia',
            field=models.CharField(default='Perú', max_length=50),
        ),
    ]
